# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Loom is not yet fully compatible with the configuration cache.
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=1.21.11

# Mod metadata
mod_id=fiw-clock
archives_base_name=fiw-clock
mod_version=1.0.0
maven_group=com.fiw

# Toolchain
kotlin_version=2.4.0
loom_version=1.16-SNAPSHOT
moddev_version=2.0.141

# Fabric (https://fabricmc.net/develop)
fabric_loader_version=0.19.3
fabric_api_version=0.141.4+1.21.11
fabric_kotlin_version=1.13.12+kotlin.2.4.0

# NeoForge (https://neoforged.net)
neoforge_version=21.11.42
kotlin_for_forge_version=6.1.0
